name: Space Race
favicon: null
layout_spectrum: 0.25665
typography_spectrum: 0.80223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c8a93'
    - '#242628'
    - '#a0aeb5'
    - '#5e6971'
    - '#c7cfd3'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
