name: Space Race
favicon: null
layout_spectrum: 0.18515
typography_spectrum: 0.94774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16181c'
    - '#414842'
    - '#53605b'
    - '#888478'
    - '#ac9a71'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
