name: Space Race
favicon: null
layout_spectrum: 0.37587
typography_spectrum: 0.7898973943665624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#914e71'
    - '#336a8e'
    - '#be9e9b'
    - '#d9d1a9'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
